### ISSUE TITLE
preset: Gruvbox Dark (official)

### ISSUE THREAD

**Issue by yatinlala** [GradienceTeam/Community#106]
### Issue

Applying the official Gruvbox Dark preset in Gradience results in a broken GTK file picker sidebar.

### Screenshots

![image](https://github.com/GradienceTeam/Community/assets/43100192/6a2c95b6-4fa9-4180-9f73-84be13bd9909)

### OS

Arch Linux

### Version

0.8.0-beta1

### Installation method

AUR

### Additional context

Using `gradience-git` package from AUR. Behaviour has been replicated on the `gradience` package in the AUR as well.

### Did you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/GradienceTeam/Gradience/blob/main/CODE_OF_CONDUCT.md).

**Comment by 0xMRTT** [comment]
If you are using gradience > 0.5, set sidebar preferneces

**Comment by yatinlala** [comment]
I didn't realize those were unset by the official theme in the latest version. Thanks for the help!

**Comment by yatinlala** [comment]
I didn't realize those were unset by the official theme in the latest version. Thanks for the help!
