### ISSUE TITLE
preset: Rosé Pine theme not applying to nautilus sidebar 

### ISSUE THREAD

**Issue by fqidz** [GradienceTeam/Community#114]
### Issue

Idk whats wrong but the sidebar for the nautilus file manager is not applying the theme. It's just using the default theme.

### Screenshots

![309042892-cdadd18e-da33-45a9-a2c0-f9bb1f9769de](https://github.com/GradienceTeam/Community/assets/82884264/37550f5a-0cd5-419e-9c6d-6cd93709e7fb)

### OS

Fedora 39

### Version

0.4.1

### Installation method

Flatpak from Flathub

### Additional context

gnome shell 45.4
adw-gtk3 v5.2

### Did you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/GradienceTeam/Gradience/blob/main/CODE_OF_CONDUCT.md).

**Comment by daudix** [comment]
You need to use nightly and manually set sidebar and secondary sidebar colors, presets aren't updated yet
