### ISSUE TITLE
One Dark theme

### ISSUE THREAD

**Issue by ByteDrummer** [GradienceTeam/Community#15]
I'd like the One Dark theme to be added. There is an existing repo for it: https://github.com/lonr/adwaita-one-dark

**Comment by daudix-UFO** [comment]
I can make it ;)

**Comment by daudix-UFO** [comment]
Smol question, is there one light?

**Comment by ByteDrummer** [comment]
I haven't seen a light version of the desktop theme, but there are light variants for code editors. For example, here's the one for Neovim: https://github.com/navarasu/onedark.nvim/blob/master/lua/onedark/palette.lua. The "dark" color palette corresponds to the same adwaita-one-dark theme colors, while "light" is the light variant. I guess you could Ctrl+F each of these colors inside the .json file and replace them with the light counterpart.

**Comment by daudix-UFO** [comment]
There are One Dark merged in the repo, but still, I will make my variant :P
