### ISSUE TITLE
feat: Catppuccin presets

### ISSUE THREAD

**Issue by AliGaygisiz** [GradienceTeam/Community#37]
### Feature description

There is already catppuccin frappe and latte presets, is there any chance you can add other catppuccin flavours like mocha?

### Did you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/GradienceTeam/Gradience/blob/main/CODE_OF_CONDUCT.md).

**Comment by daudix-UFO** [comment]
Thank you, will make it soon ;)

**Comment by daudix-UFO** [comment]
I will re-create all catppuccin variants ;)

https://github.com/catppuccin/catppuccin/blob/main/docs/style-guide.md

**Comment by daudix-UFO** [comment]
Take a look :D

### Latte

![Latte](https://user-images.githubusercontent.com/77155297/189545336-74f5d856-4b0f-4556-8523-28544c557034.png)

### Farppe

![Frappe](https://user-images.githubusercontent.com/77155297/189545333-90cdf0f1-c845-400c-bc11-f6b2a8c5e795.png)

### Macchiato

![Macchiato](https://user-images.githubusercontent.com/77155297/189545331-e6f95ebd-51e7-4417-ae49-931ec6660adc.png)

### Mocha

![Mocha](https://user-images.githubusercontent.com/77155297/189545326-8dd422db-00b1-4685-a71e-850e33bac0fe.png)

**Comment by 0xMRTT** [comment]
Niceeee

**Comment by daudix-UFO** [comment]
One of my favourite palettes :)

**Comment by 0xMRTT** [comment]
Btw, did you noticed an issue with Firefox GNOME Theme plugin .?

All drop-down are transparent and I don't know how to fix that

**Comment by daudix-UFO** [comment]
> Btw, did you noticed an issue with Firefox GNOME Theme plugin .?
> 
> All drop-down are transparent and I don't know how to fix that

I don't really tested it yet :/

**Comment by daudix-UFO** [comment]
@AliGaygisiz Is it OK?

**Comment by daudix-UFO** [comment]
If not I will reopen ;)

**Comment by AliGaygisiz** [comment]
Of course it is OK! Thank you so much.

**Comment by 0xMRTT** [comment]
🚀🎉👌

**Comment by AliGaygisiz** [comment]
Just a minor report.
![Screenshot from 2022-09-12 12-15-27](https://user-images.githubusercontent.com/30773603/189617401-b3f2cab7-1724-48c7-9cff-f9b99b6b87eb.png)
On and off state colors on switches are hard to distinguish.

**Comment by daudix-UFO** [comment]
Tested it (yes, only now, sorry), and this problem is in every preset, will use a bit different color

**Comment by daudix-UFO** [comment]
I think it fixed now

**Comment by AliGaygisiz** [comment]
Thanks for the update! I tried the updated preset now, everything seemed great at first but now the hover highlight on right click menus are hiding texts.

https://user-images.githubusercontent.com/30773603/191363468-eda37e60-1a1f-4907-b717-e3d81118d02b.mp4

**Comment by daudix-UFO** [comment]
I will try to find a middle colour, both visible in switches and right click menu

**Comment by daudix-UFO** [comment]
Following [Catppuccin Style Guide](https://github.com/catppuccin/catppuccin/blob/main/docs/style-guide.md) I can't make switches contrast and keep text visible in menus :(

**Comment by daudix-UFO** [comment]
I suggest you to replace the accent color with one you like: https://github.com/catppuccin/catppuccin/blob/main/docs/style-guide.md#regular-colours

**Comment by daudix-UFO** [comment]
We still need solution, so I will keep this open for now :(

**Comment by AliGaygisiz** [comment]
It's okay. Now i'm using previous version of your preset. You can revert the preset to that version if you want, texts in menus are much more important than switch colors.

**Comment by daudix-UFO** [comment]
I already did this, but I will try to make something with it
