### ISSUE TITLE
preset: This is a test of preset request

### ISSUE THREAD

**Issue by daudix-UFO** [GradienceTeam/Community#38]
### Preset description

Hello, I want to test this, here is the link to Solarized: https://ethanschoonover.com/solarized/

### Additional Context

I want it a bit more saturated, maybe by 10%

### Did you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/GradienceTeam/Gradience/blob/main/CODE_OF_CONDUCT.md).

**Comment by 0xMRTT** [comment]
Why ?

**Comment by daudix-UFO** [comment]
OK, this works very good 👍

**Comment by daudix-UFO** [comment]
Just tested is it assigns me
