### ISSUE TITLE
Create a workflow to automatically update presets.json

### ISSUE THREAD

**Issue by tfuxu** [GradienceTeam/Community#4]
A simple CI action that would fetch a name and raw link of a newly added preset should be enough.

Also, there could be added a workflow that would check before merging a PR if a preset doesn't have any JSON errors in it. Here's a popular linter that could be used for it: https://github.com/zaach/jsonlint

**Comment by tfuxu** [comment]
> A simple CI action that would fetch a name and raw link from a newly added preset should be enough.
> 
> Also, there could be added a workflow that would check before merging a PR if a preset doesn't have any JSON errors in it. Here's a popular linter that could be used: https://github.com/zaach/jsonlint

**Comment by 0xMRTT** [comment]
I've got the same idea :D

**Comment by 0xMRTT** [comment]
Idea:

1. A workflow create a `in-presets.json` with all presets stored in the repo
2. Presets stored outside are added by users in `out-presets.json`
3. Another workflow merge two presets files in `presets.json` and run `jsonlint`

**Comment by tfuxu** [comment]
> 1. A workflow create a `in-presets.json` with all presets stored in the repo

Wouldn't it be simpler to just append `presets.json` with new values? 

> 2. Presets stored outside are added by users in `out-presets.json`

For presets stored outside, maybe a better approach than a current one would be to allow users to have their own repositories of presets, and as we now have preferences in Gradience, we could put here a option to provide a custom `presets.json` location for user-defined preset repositories.

**Comment by 0xMRTT** [comment]
Oh great idea 💡

We can add a dconf key with a list of all repos (gradience official repo will be first and if the user disable all repo it will be selected ? Or gradience will say "no repo" ?)

**Comment by tfuxu** [comment]
> We can add a dconf key with a list of all repos (gradience official repo will be first and if the user disable all repo it will be selected ? Or gradience will say "no repo" ?)

That's actually a pretty hard question. One the one side, a list with custom repos hardcoded into Gradience would allow users to discover interesting presets, but on the other side, after some time that list will become too big to be scrollable in preferences.

**Comment by 0xMRTT** [comment]
We can implement a kind of pagination like in Extension Manager and a search

**Comment by tfuxu** [comment]
> We can implement a kind of pagination like in Extension Manager and a search

We can add something like 'Repositories' tab in presets manager so user will have a easy way to enable a repository if it is on any of our databases (so probably something with the same format as `presets.json` with a name of repository and a link), and add an option in preferences to add custom repositories that are not available from presets manager.

**Comment by 0xMRTT** [comment]
Sounds gøød 👍

**Comment by daudix-UFO** [comment]
Also an action to merge `official` and `curated` and put this in `presets.json` in `main`

**Comment by daudix** [comment]
After 215 days, a lot of manual edits of preset list files, endless amount of json f'ups, the automatic preset list generation is here for both for `next` and `main` :partying_face: :tada:

Thanks to @dominichayesferen for making this possible!
