### ISSUE TITLE
propose: Create custom presets template repository

### ISSUE THREAD

**Issue by tfuxu** [GradienceTeam/Community#54]
## Why?
Creating a template repository, will allow users to generate new custom presets repositories, with a unified look and structure, and without a need to create additional commits to remove official presets, as template repository will be a empty structure that can be populated with just one commit.

## Implementation
I've created a template repository that I can transfer later to GradienceTeam organization, if this proposal will be accepted: https://github.com/tfuxu/Community-template

### Did you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/GradienceTeam/Gradience/blob/main/CODE_OF_CONDUCT.md).

**Comment by daudix-UFO** [comment]
I like this idea!

**Comment by 0xMRTT** [comment]
Could you move the repo ?

**Comment by tfuxu** [comment]
> Could you move the repo ?

sure

**Comment by tfuxu** [comment]
@0xMRTT
I need a permission to create public repositories in our org.
![Screenshot from 2022-09-30 23-12-45](https://user-images.githubusercontent.com/73042332/193357039-7226bfbd-6cb5-445e-aead-26b5c21b3246.png)

**Comment by 0xMRTT** [comment]
Fixed

**Comment by tfuxu** [comment]
Okay, transferred.

**Comment by 0xMRTT** [comment]
Nice 😎
