### ISSUE TITLE
bug:  Theme is applied partially

### ISSUE THREAD

**Issue by marcinjahn** [GradienceTeam/Community#56]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I've been trying to apply a theme called "Alpha Mac". When I select the theme in Gradience, the Gradience window becomes properly themed:

![image](https://user-images.githubusercontent.com/10273406/194896886-1178b062-da0a-401a-aa3a-d9cb04102678.png)

However, when I log out and log back in, I see that:

- window backgrounds follow the theme (not all apps though)
- window controls (close, maximize) have 3 possible states:
  - in some apps they follow the Alpha Mac theme
  - in some apps they look like Adwaita (even though the rest of the theme is applied, like a background)
  - in some apps windows controls disappear completely, although they are still clickable

The window controls issue is kinda random. A given app may not display controls at all, and after another log out - log in, the controls are visible (but in the default Adwaita style).

### To Reproduce

1. Apply Alpha Mac theme

### Expected behavior

The theme should just work across all the apps.

### OS

Fedora Linux 36 (Workstation)

### Version

0.3.1

### Installation method

Flatpak from Flathub

### Additional context

![image](https://user-images.githubusercontent.com/10273406/194897825-9e000178-a9c3-47c2-ad01-d54b077b2e08.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tfuxu** [comment]
>     1. a community theme Alpha Mac (possibly Alpha Black and Alpha Dark as well) is broken?
> 
>     2. Gradience does not show that the theme is broken until I apply it and logout/login.

1. Yea, it is,
2. The preset itself isn't broken, it's just that CSS parser is loading it in a broken way
