### ISSUE TITLE
preset: Tokyo Night

### ISSUE THREAD

**Issue by noahdotpy** [GradienceTeam/Community#67]
### Preset description

This is a dark theme and a light theme that has a few variants such as: storm, night, moon, day. The link to the original color-scheme for Neovim is https://github.com/folke/tokyonight.nvim. This is a popular color-scheme for VSCode also!

### Additional Context

I personally would like to see the `night` variant the most.

### Did you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/GradienceTeam/Gradience/blob/main/CODE_OF_CONDUCT.md).

**Comment by daudix-UFO** [comment]
Thank you for request, I will try to make one soon ;)

**Comment by daudix-UFO** [comment]
Added Tokyo Night presets in https://github.com/GradienceTeam/Community/commit/f73a440f37edc45cc1071883e5cf3ddc56c8295a, check them out :wink:

**Comment by daudix-UFO** [comment]
### Light
![Light](https://user-images.githubusercontent.com/77155297/204800797-a8559b4a-58ae-44c3-94e5-c14a8d378a51.png)

### Dark
![Dark](https://user-images.githubusercontent.com/77155297/204800828-6876802a-23cc-479f-a953-f7f3b3a6a959.png)

### Storm
![Storm](https://user-images.githubusercontent.com/77155297/204800862-f75e05fc-0999-4390-9033-b7a976a4abdd.png)

### Moon
![Moon](https://user-images.githubusercontent.com/77155297/204800887-2b35e956-88dc-4355-b947-b5c54ea11b34.png)

**Comment by daudix-UFO** [comment]
Closing, if you want to change something ping me
