### ISSUE TITLE
Gruvbox theme

### ISSUE THREAD

**Issue by vanillajonathan** [GradienceTeam/Community#8]
I would like a theme with the Gruvbox palette.

https://github.com/morhetz/gruvbox-contrib#palette

**Comment by arslee07** [comment]
my attempt: #9

**Comment by vanillajonathan** [comment]
@arslee07 Great! It would be even better if there was a `gruvbox-light.json` and and a `gruvbox-dark.json` preset.

**Comment by daudix-UFO** [comment]
I will create light/dark preset and polish it if needed 😉

**Comment by vanillajonathan** [comment]
@daudix-UFO Please do!

**Comment by daudix-UFO** [comment]
What about this?

![Снимок экрана от 2022-09-05 00-57-33](https://user-images.githubusercontent.com/77155297/188334998-26f9b71a-f52d-48a3-b4d3-628a5904094d.png)
![Снимок экрана от 2022-09-05 00-57-24](https://user-images.githubusercontent.com/77155297/188334999-57335224-9ff9-4d3a-98c2-a6e0642aa84a.png)

**Comment by daudix-UFO** [comment]
I can change some colors if needed, then I will create a PR ;)

**Comment by daudix-UFO** [comment]
Created PR: #23
