### ISSUE TITLE
preset: Night-Owl

### ISSUE THREAD

**Issue by Deep7k** [GradienceTeam/Community#91]
### Preset description

As Gradience doesn't have many high contrast theme. I suggest to add the Night owl theme which is widely ported high contrast theme

[VSCode](https://github.com/sdras/night-owl-vscode-theme)

[Gnome-Terminal (Color palette)](https://github.com/Gogh-Co/Gogh/blob/master/themes/Night%20Owl.yml)

### Did you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/GradienceTeam/Gradience/blob/main/CODE_OF_CONDUCT.md).

**Comment by daudix** [comment]
Thanks for request, I'm gonna try to create one soon ;)

**Comment by daudix** [comment]
Added in https://github.com/GradienceTeam/Community/commit/3c051d7a15dd28526a23f422e280066cb2e9ebe9, tell me if you have any suggestions ;)
